# Generated by Django 5.2.4 on 2025-09-25 11:08

import backend.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_result_marks'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', backend.core.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ARTIST', 'Artist'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
